import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { BaseLayoutProps } from '@/types/types'
import { ToastContainer } from 'react-toastify';

import { Header } from '@/components/index';

import './globals.scss'

import {QueryClientProvider}  from '@/providers/QueryClientProvider'

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: BaseLayoutProps ) {
  return (
      <html lang="en" >
          <body className={poppins.className}>
              <QueryClientProvider>
                  <Header/>
                  <main className="mx-auto max-w-7xl px-5 xl:px-0 ">
                      {children}
                  </main>
              </QueryClientProvider>
              <ToastContainer />
          </body>
    </html>
  )
}
